### ISSUE TITLE
maybe need update ...

### ISSUE THREAD

**Issue by adryserage** [flagrow/console#2]
when running `composer require flagrow/console
`
give error : 
```

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for flagrow/console ^0.3.0 -> satisfiable by flagrow/console[0.3].
    - flagrow/console 0.3 requires flarum/core ^0.1.0-beta.8 -> satisfiable by flarum/core[0.1.x-dev] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

PS: i have the latest Flarum version

maybe i juste dont understand the simple error i juste want explanation to please !

**Comment by clarkwinkelmann** [comment]
version 0.3 of console requires beta8, which isn't out yet. And composer doesn't handle that well...

You can install version 0.2 with `composer require flagrow/console:^0.2`.

Just a heads up: that packages doesn't do anything by itself and doesn't make sense to install manually. It only makes sense as a dependency of another extension which uses its features. In which case the developer should define which version they need in their extension dependencies :wink:
